<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\QueryException;

class Ranchito extends Model
{
    use HasFactory;
    public static function createRanchito(int $id, string $url,string $descripcion){
        $ranchito = new Ranchito;
        $ranchito->id = $id;
        $ranchito->imagen = $url;
        $ranchito->descripcion = $descripcion;
        $ranchito->save();
    }

    public static function createRanchitos(){
        try{
            Ranchito::createRanchito(Ciudad::query()->select("id")->where("nombre","Cuitzeo")->first()->id,"https://imagenescityexpress.scdn6.secure.raxcdn.com/sites/default/files/2018-01/cuitzeo-michoacan.jpg","En el limite de estado con Guanajuato, uno de los pueblos mágicos Michoacán, fundado por los agustinos, que en purépecha su nombre significa 'lugar de tinajas'. Se ha dicho que esta zona fue un centro ceremonial para varias culturas prehispánicas como lo fue la teotihuacana, la tolteca y la purépecha. Esta última construyo la actual zona arqueológica Tres Cerritos, así que no dudes visitarla, como también el Templo de Guadalupe y la zona termal de Huandacareo. Puedes conocer también el convento agustino de Santa María Magdalena, este se empezó a construir en 1550 con un aspecto de fortaleza medieval, es increíble. Cuitzeo puede presumir el tener uno de los lagos más asombrosos y extensos de México, además de ser el hábitat de diversas especies de aves. Degusta unos deliciosos charales, lechones, ancas de rana o un riquísimo mole de guajolote, te aseguro que la gastronomía michoacana es impresionante. En el pueblo existe una antigua leyenda acerca del lago, se dice que este fue formado gracias al llanto de la princesa Hapunda cuando perdió a su amado.");
            Ranchito::createRanchito(Ciudad::query()->select("id")->where("nombre","Jiquilpan")->first()->id,"https://www.lacapital.com.mx/files/news/jiquilpan_mich.png","De seguido, conocida como la ciudad de las jacarandas, su nombre de origen náhuatl significa 'lugar del añil', uno de los lugares mágicos en Michoacán. La población tuvo gran importancia como centro agrícola, comercial y cultural. Tanto que llegó a ser calificado como un importante productor de seda en el mundo. Para que conozcas una parte de su historia, visita el museo en el Centro de Estudios Históricos de la Revolución Mexicana 'Lázaro Cárdenas'. En tu itinerario no olvides visitar el Templo del Sagrado Corazón, aquí podrás encontrar un mural pintado por el discípulo de José Clemente Orozco. Asimismo, puedes apreciar de una magnifica vista de la ciudad desde la biblioteca Casa de Piedra, y no olvides comprar alguna artesanía, yo amo sus rebozos. Y después del viaje puedes disfrutar de unas clásicas carnitas de cerdo, un caldo cosechero, la morisqueta, un pozole de elote o unos uchepos. Cabe mencionar que, aquí en 1895, nació Lázaro Cárdenas del Río, quien fuera Gobernador del estado de Michoacán y Presidente de la República de 1934 a 1940.");
            Ranchito::createRanchito(Ciudad::query()->select("id")->where("nombre","Mineral de Angangueo")->first()->id,"https://doorwaytomexico.com/wp-content/uploads/2019/04/Michoac%C3%A1n.jpg","Declarado Pueblo Mágico en el 2012, se ubica en la Sierra Madre Oriental, así pues, su nombre significa “pueblo entre montañas”, “dentro del bosque” o “cosa muy alta”. De hecho es un poblado con un pasado muy importante en la minería, pero en la actualidad da lugar a un fenómeno que a mí en lo personal me maravilla demasiado. La mariposa monarca lo eligió santuario, así que es muy común que durante algunos meses del año vas a lograr apreciar a estas hermosas criaturas. Obviamente, entre sus atractivos encontrarás la Reserva de la Biosfera Mariposa Monarca, también puedes visitar el Santuario el Rosarito y la Casa Parker. Conoce el Templo de la Inmaculada Concepción, la Parroquia de San Simón Celador y no olvides el Túnel turístico San Simón. Por otro lado, disfruta de un exquisito platillo de mole de guajolote, o porqué no unos taquitos de barbacoa de borrego y prueba el pozole de trigo. ¿Sabías que las mariposas monarcas con los únicos insectos que migran hasta más de 4,500 kilómetros para salir del clima frío y comenzar la hibernación?");
            Ranchito::createRanchito(Ciudad::query()->select("id")->where("nombre","Paracho de Verduzco")->first()->id,"https://www.gob.mx/cms/uploads/article/main_image/102845/Paracho__Mich_Mx__2_.jpg","Se trata de uno de los lugares turísticos de Michoacán, el nombre Paracho proviene de una palabra chichimeca que significa “ofrenda”. Conocida como la capital de la guitarra desde el siglo XVI pues la comunidad elabora estos instrumentos de cuerda de muy alta calidad. Actualmente, es denominado Pueblo Mágico y fue gracias al nombramiento que se llevó acabo en el 2020, sumando así 132 pueblos mágicos, ¡bienvenido! Entre los atractivos hallarás talleres de Laudería, paseos ecoturísticos y podrás visitar el Templo de San Jerónimo Arantza, así como el de Santiago Apóstol. ¿Sabías que la gastronomía michoacana es reconocida como Patrimonio Intangible de la Humanidad desde 2010? Así que, podrás degustar de deliciosos manjares. Y por si no fuera poco, como te conté es reconocido mundialmente por las guitarras, tanto que fue inspiración para elaborar la guitarra en la película “Coco” de Disney.");
            Ranchito::createRanchito(Ciudad::query()->select("id")->where("nombre","Patzcuaro")->first()->id,"https://mediaim.expedia.com/destination/1/3f7ba8bbc7e42f29405aefb75efe8568.jpg","Un pueblo que data del siglo XIV fundada por los purépechas o tarascos. Su nombre significa “la puerta del cielo” y se cree que fue la capital religiosa de los purépechas pues se creía que aquí ascendían y descendían los dioses. Seguramente no tendrás tiempo de aburrirte ya que puedes disfrutar de una visita por sus calles empedradas entre los edificios de color blanco con los tejados rojos. Además, conoce los portales de la Plaza Vasco de Quiroga, la casa de los ocho patios, sus iglesias de estilo barroco y neoclásico o su muy famoso lago. No olvides probar algunas de sus delicias típicas como los charales fritos, unas ricas corundas rellenas o un pescado blanco del mismísimo lago de la localidad. Cabe mencionar que las tradiciones locales como el día de muertos y la Pirekua son Patrimonio Nacional de la Humanidad declarados por la UNESCO. Por otra parte, aquí mismo se encuentra la segunda plaza colonial más grande de México.");
            Ranchito::createRanchito(Ciudad::query()->select("id")->where("nombre","Santa Clara del Cobre")->first()->id,"https://www.gob.mx/cms/uploads/article/main_image/86510/Michoacan_Santa-clara-de-cobre_Artesania-en-Los-portales-web.jpg","Característico por la tradición de transformar el cobre en recuerdos, gracias a los artesanos de la localidad. En 1553 los frailes españoles fundaron el pueblo, el Tata Vasco fue quien impulso la especialización en cobre donde todo habitante participaba en la actividad. Plasmado su nombre en muchos de los atractivos que encontrarás, por ejemplo, admira su plaza, el kiosco cuenta con un techo de cobre. No te puedes perder la oportunidad de conocerlo, puedes pasear en bicicleta o si lo prefieres podrás pescar, ¿y que tal eres para las aventuras? Puedes realizar un recorrido en kayak, deslízate por una tirolesa o intérnate en el bosque entre sus puentes colgantes, ¿apoco no suena increíble y lleno de emoción? Entre los platillos locales degusta de lo típicos charales, las corundas y las tortas de tostada o las tostadas de carne apache.");
            Ranchito::createRanchito(Ciudad::query()->select("id")->where("nombre","Tacámbaro")->first()->id,"https://www.gob.mx/cms/uploads/article/main_image/86089/Tacambaro-la-Alberca-web.jpg","La naturaleza es la protagonista de este escenario, este es uno de los pueblos cercanos a Pátzcuaro, se trata de un pueblo mágico declarado en 2012. Conocido también como el Balcón de Tierra Caliente, su nombre purépecha significa “Lugar de Palmeras” y cuenta con hermosos edificios coloniales y casonas. Entre las artesanías que encontrarás van a ser huaraches, sillas de montar, fuetes, servilletas bordadas, macetas de barro, artículos de herrería, y muchísimos más. Uno de los atractivos históricos que podrás conocer es el santuario de Nuestra Señora de Fátima, muy famoso por sus cuatro pinturas de las vírgenes refugiadas. Así como también el Centro Cultural Amalia Solórzano, la Catedral de San Jerónimo, el Templo de Fátima y la Capilla de Santa María Magdalena. Además, cuenta con una zona ecoturística donde se encuentra el Parque Cerro Hueco, la Laguna de Magdalena, la Cascada de Santa Paula y la Alberca. Cabe mencionar que la Alberca es uno de los tres cráteres volcánicos llenos de agua con los que cuenta el estado. Tacámbaro es considerada como “Ciudad heroica” después de que en 1865 las fuerzas del general Nicolás de Régules vencieron a los soldados belgas. Y, por si no fuera poco la ciudad también fungió como capital del estado en dos ocasiones, una fue en el año de 1865 y después en 1915.");
            Ranchito::createRanchito(Ciudad::query()->select("id")->where("nombre","Tlalpujahua")->first()->id,"https://mexicorutamagica.mx/wp-content/uploads/2021/11/feria-esfera-tlalpujahua.jpg","Tlalpujahua de Rayón, conocido muy comúnmente como el pueblo navideño de México por la impresionante producción de hermosas esferas artesanales. Se incorporó a la lista de pueblos mágicos en 2005. Su nombre de origen náhuatl significa “tierra de tezontle” y fue habitado por los mazahuas. Después, en la época colonial se convirtió en un centro de explotación de oro y plata. Aquí nació Ignacio López Rayón y su antigua casa se convirtió en un museo. Te invito a que visites el Santuario del Carmen del siglo XVII y las ruinas de la Capilla de Nuestra Señora del Carmen, sepultadas en 1932 por un accidente minero. Así como el Parque Nacional Rayón y sin olvidar la presa Brockman. Realiza un recorrido por “Las Dos Estrellas”, una mina del siglo XVI que ahora es un museo.Después de tanto paseo seguro deseas algo para comer, disfruta de las tradicionales corundas o de unos uchepos de cuchara y no olvides el pan de pucha.Si eres fan del cine, a inicios de octubre puedes asistir al Festival Internacional dedicado al cine fantástico, de terror y de ciencia ficción. Y, durante los meses de octubre y diciembre puedes disfrutar de la feria de la esfera.");
            Ranchito::createRanchito(Ciudad::query()->select("id")->where("nombre","Tzintzuntzan")->first()->id,"https://cdn.forbes.com.mx/2020/10/Tzintzuntzan-Pueblo-Ma%CC%81gico-2-1-e1602784900656-640x360.jpg","¿Qué quiere decir la palabra tzintzuntzan? Realmente hay pueblos mágicos cerca de Morelia y este no es la excepción, heredero de la cultura purépecha, su nombre significa “lugar de colibríes”. Actualmente, la comunidad es reconocida por el trabajo artesanal en materiales como el tule, el barro, la madera y la cantera. De igual manera conservan mucho sus tradiciones prehispánicas, así como el Día de Muertos, las danzas de los paloteros y el ritual de velación en el panteón. Su principal atractivo son cinco basamentos piramidales conocidos como las Yácatas que datan del siglo XII las cuáles podrás visitar y conocer. Igualmente, puedes explorar las islas de la Pacanda, el Museo Exconvento de Santa Ana y el Antiguo Hospital de Indios. Para complementar tu visita disfruta de un caldo ahogado, un rico atole de grano, tal vez una corunda o el churipo de pescado. No olvides conocer el convento de San Francisco del siglo XVI, se cuenta que los olivos que crecen en el atrio fueron plantados por el obispo Vasco de Quiroga. Sin duda es uno de los pueblos mágicos de Michoacán que no puedes perderte.");
        }catch (QueryException $exception){
            return false;
        }
    }


    #App\Models\Ranchito::create(
    #10,"https://imagenescityexpress.scdn6.secure.raxcdn.com/sites/default/files/2018-01/cuitzeo-michoacan.jpg",
    #"En el limite de estado con Guanajuato, uno de los pueblos mágicos Michoacán, fundado por los agustinos, que en purépecha su nombre significa 'lugar de tinajas'. Se ha dicho que esta zona fue un centro ceremonial para varias culturas prehispánicas como lo fue la teotihuacana, la tolteca y la purépecha. Esta última construyo la actual zona arqueológica Tres Cerritos, así que no dudes visitarla, como también el Templo de Guadalupe y la zona termal de Huandacareo. Puedes conocer también el convento agustino de Santa María Magdalena, este se empezó a construir en 1550 con un aspecto de fortaleza medieval, es increíble. Cuitzeo puede presumir el tener uno de los lagos más asombrosos y extensos de México, además de ser el hábitat de diversas especies de aves. Degusta unos deliciosos charales, lechones, ancas de rana o un riquísimo mole de guajolote, te aseguro que la gastronomía michoacana es impresionante. En el pueblo existe una antigua leyenda acerca del lago, se dice que este fue formado gracias al llanto de la princesa Hapunda cuando perdió a su amado.")
    #\App\Models\Ranchito::create(11,"https://www.lacapital.com.mx/files/news/jiquilpan_mich.png","De seguido, conocida como la ciudad de las jacarandas, su nombre de origen náhuatl significa 'lugar del añil', uno de los lugares mágicos en Michoacán. La población tuvo gran importancia como centro agrícola, comercial y cultural. Tanto que llegó a ser calificado como un importante productor de seda en el mundo. Para que conozcas una parte de su historia, visita el museo en el Centro de Estudios Históricos de la Revolución Mexicana 'Lázaro Cárdenas'. En tu itinerario no olvides visitar el Templo del Sagrado Corazón, aquí podrás encontrar un mural pintado por el discípulo de José Clemente Orozco. Asimismo, puedes apreciar de una magnifica vista de la ciudad desde la biblioteca Casa de Piedra, y no olvides comprar alguna artesanía, yo amo sus rebozos. Y después del viaje puedes disfrutar de unas clásicas carnitas de cerdo, un caldo cosechero, la morisqueta, un pozole de elote o unos uchepos. Cabe mencionar que, aquí en 1895, nació Lázaro Cárdenas del Río, quien fuera Gobernador del estado de Michoacán y Presidente de la República de 1934 a 1940.");
}
